export default {
  login: "dsimdev",
  id: 61282565,
  node_id: "MDQ6VXNlcjYxMjgyNTY1",
  avatar_url: "https://avatars.githubusercontent.com/u/61282565?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/dsimdev",
  html_url: "https://github.com/dsimdev",
  followers_url: "https://api.github.com/users/dsimdev/followers",
  following_url: "https://api.github.com/users/dsimdev/following{/other_user}",
  gists_url: "https://api.github.com/users/dsimdev/gists{/gist_id}",
  starred_url: "https://api.github.com/users/dsimdev/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dsimdev/subscriptions",
  organizations_url: "https://api.github.com/users/dsimdev/orgs",
  repos_url: "https://api.github.com/users/dsimdev/repos",
  events_url: "https://api.github.com/users/dsimdev/events{/privacy}",
  received_events_url: "https://api.github.com/users/dsimdev/received_events",
  type: "User",
  site_admin: false,
  name: "Damián Simón",
  company: null,
  blog: "https://www.linkedin.com/in/damiansimon/",
  location: "Buenos Aires",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "dsimdev",
  public_repos: 20,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-02-20T14:30:43Z",
  updated_at: "2023-03-01T15:40:04Z",
};
